//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int id { get; set; }
        public string PackageName { get; set; }
        public string PackageDesc { get; set; }
        public decimal Price { get; set; }
        public int Duration { get; set; }
        public int PackageDetailsDAOId { get; set; }
    }
}
